= J-Confs 

image:https://travis-ci.org/13tomoore/J-Confs.svg?branch=master["Build Status", link="https://travis-ci.org/13tomoore/J-Confs"]

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 Apprentissage).

The code is hereby published under the *MIT License*, with their permission. +

This project is producted by 5 students : link:https://github.com/aliliKM[Alison KOUDOUSSOU MESSAN], link:https://github.com/jacquesmoati[Jacques MOATI], link:https://github.com/13tomoore[Tom MOORE], link:https://github.com/nikolaspaci[Nikola SPACI] and link:https://github.com/feLlx[Félix VITAS].

=== Delivery schedule for 2019

[width="80%",cols="^7,^7,^8,^9,18",options="header"]
|=========================================================
|Delivery | Deadline | Expected effort | SM/PO | TEAMS

|1|20th May, 2019 |10 h | link:https://github.com/feLlx[Félix Vitas] |Team 1 : Alison & Jacques +
Team 2 : Nikola & Tom 
|2| 3rd June, 2019 |15 h | link:https://github.com/jacquesmoati[Jacques MOATI]| Team 1 : Alison & Tom +
Team 2 : Nikola & Félix

|3|17th June, 2019 | 10 h | link:https://github.com/aliliKM[Alison Koudossou Messan]| Team 1 : Nikola & Tom +
Team 2 : Jacques & Félix

|4|17th June, 2019 | 10 h | link:https://github.com/nikolaspaci[Nikola Spaci]| Team 1 : Alison & Tom +
Team 2 : Jacques & Félix


|=========================================================

=== Delivery 1

	* *Tasks done*
	
		. Draw the outlines of the project we expect at the end of the semester.
		
		. Creation of a repository for everyone using a __fork__ on GitHub (C), you can find it link:https://github.com/13tomoore/J-Confs[here].
		
		. The SM/PO writes in the README.adoc of the project, write there the outline of the four iterations, with more details for the coming iterations.
		
		. Uptade dependencies in the POM.xml, especially check link:https://github.com/google/guava[Guava]. 
		
		. Clean repository : gitignore, Move the old docomentation (in the former folder "Présentation") in a folder called '*Doc*', delete useless files.
		
		. Enumerate the classes, methods and interfaces that have been done in the previous project, established what is working and what is not working (answer why), what could be done (excel sheet on our Google Drive.
		
		. Create a new branch called '*dev*' on GitHub repository.
		
		. Resolve link:https://travis-ci.org/[Travis] Build


=== Delivery 2 
	* *Tasks done*
	    . The SM/PO rewrite the README.adoc of the project, with much more details about the task for "TASK TO DO" in the curent iteration. +
	    Write a clean README.adoc with asciidoc format. 
	    
	    . Write an email @ __Jean-Christophe Gay__ asking him clear explanation of how to access to the intranet of the Université Paris-Dauphine +
	    
	    . Resolve warnings (mostly unused libraries)
	    
	    . Check if the Build Status on link:https://travis-ci.org/[Travis] is still working
	    
	    . Improve readability of the code, use immutable object where it is intended (proceed by subject)
	    
        . Apply the best practices using Guava on the existing code. +
            e.g. for __equals__ method using Guava.
        Code JUnit test for these classes :
                *** ConferenceWriter
                *** ConferencesShower
                *** ReverseGeoCode
                
        . Apply a Javadoc with defensive programming (preconditions).
        
        . Redefine some raised exception that are too much generic.
        
        . Make a link between an ICalendar file and a researcher. 
        
        . About refactoring : 
        .. New constructors (using non Null)
        .. Immuable Conference (delete setters)
                
        . Modify *ConferenceGUI* with the possibilities :
        .. For the user to choose his ICalendar
        .. Every conferences of this ICalendar should be displayed on the screen
        .. Making possible editing a conference instead of Recreating/Deleting this conference
        ..  Making possible to display a map with the location of a conference selected and being able to search about its itinary.
        .. Writing and checking the __@annotations__


=== Delivery 3 

	* *Tasks TO DO*
	
		. The SM/PO update the README.adoc of the project with asciidoc format. 
		
		. Write a file in asciidoc format rewriting the  @ __Jean-Christophe Gay__ explaination (@ __Olivier Cailloux__)
								
        . Check if we can execute the app using one single __main__
            
        . About refactoring : 
	        .. See and change automatic changes of bottow on the graphic interface
	        .. GUI Patterns         
	        .. Resolve new warnings
	        .. Update JUnit 5 dependencies on the POM.xml
	        .. Create packages
	        .. Delete unused classes (such as IO, an empty class)
	              
        . News : 
         	.. Export an ics file to github
         	.. Store a github file
         	.. Advance on the map (distance and path between the two points)  	

=== Delivery 4 

	* *Tasks*
		. The SM/PO update the README.adoc elements that we want the teacher to take into account in the overall assessment.
		. The SM/PO fix packages and format of the code. 
		. Team 1 : New feature : add and edit conferences online (https://www.fruux.com).
		. Team 2 : New feature : try to display a route to the conference location
		. Team 1 & 2 : Document the added functionality and say what has not been done, to inform the next group.