J-Confs
-------

A Java project developed by students during the https://github.com/oliviercailloux/java-course[Java course] taught at Université Paris-Dauphine (in http://www.mido.dauphine.fr/[MIDO] L3 Apprentissage).

This project is producted by 5 students : 

- https://github.com/machria[Achria Majid]
- https://github.com/sebastienbourg[Bourg Sébastien]
- https://github.com/anis468[Hamouni Anis]
- https://github.com/floryanKieffer[Kieffer Floryan]
- https://github.com/Zanis922[Zouari Anis]

=== Delivery schedule for 2020

[width="80%",cols="^10,^20,^10,^30,^10",options="header"]
|===================================================================================================================================
|Delivery |Deadline | Expected effort | TEAMS | SM/PO


|1|20th April, 2020 |13 h | Team 1 : Kieffer Floryan & Hamouni Anis + Team 2 : Achria Majid & Bourg Sébastien | Zouari


|===================================================================================================================================



Delivery 1 
~~~~~~~~~~~

For the first iteration, the team has been divided in 2 parts,  one part that is in charge of LocationIQ's package (Kieffer Floryan & Hamouni Anis),  and the other part of the team is on Calendar's package (Achria Majid & Bourg Sébastien).

*Tasks done* :

With regard to the team in charge of the *Calendar package* : 


- The team worked on the Calendar package to integrate a connection to a calendar hosted by various NextCloud platform hosts (example: cloudamo and wolki). We modified the "CalendarOnline" class and added another "CalendarBuilder" class. We also tested other architectures such as interfaces but we chose to start on a builder for more clarity and also because we were more comfortable with this architecture.

With regard to the team in charge of the *LocationIQ package* : 


- We have been working on a new Location class. To do this we imported all the source code of LocationIQ into our code. We then created the Location package specific to our project and developed the following classes: Location (Floryan Kieffer and Anis Hamouni), Direction (Anis Hamouni) and Translation (Floryan Kieffer). The Location class should allow to retrieve the information in a file (offline mode). This class may be removed later we have not yet fully implemented it. The Translation class should make it possible to return several addresses based on an imprecise information and to propose them to the user so that he can select one among the proposed choices. Following this response, a process of deleting unnecessary addresses is carried out. Then we will have in this class all the necessary information about the address selected by the user.

- About the Direction class : this class is used to calculate the distance and time between two locations, as well as the path to take to get there. For the moment the locations are strings in {longitude, latitude} format, later on they will be attributes of type Location. Concerning the steps for the move, we have a function to return the necessary data for this move, the concern is that there is a lot of useless information, we have sorted it but it is not yet sufficient.


Delivery 2 
~~~~~~~~~~~

- LocationIQ : solve open issues -> review LocationIQ API architecure, finish implementation of TranslationAddress and Direction

- Calendar : new architecture with a builder to implement and solve open issues

- Use Instant, use double instead of Double and use a Builder in Conference.

- Delete package io.github.oliviercailloux.geocode 

If enougth time : 

- Extend the ability to register a fee (registrationFee) of a conference to able different prices : student price, early registration fee, member price, ...
- Clean ressources (16 MB in src/main/resources/io/github/oliviercailloux/jconfs)
