= Evolution, fruux and J-Confs

The purpose of this file is to document the use of Evolution and J-Confs in relation to Fruux, i.e. to explain which manipulations 
are possible on a Fruux calendar, either from the Evolution application or from the J-Confs software. +
It is also a question of explaining the synchronization relationships between Evolution and J-Confs. In other words, will a modification made in Evolution be visible in J-Confs and vice versa?

In order for the reader to be able to perform the modification tests of a calendar, here are the pointers that can be useful + 
*Fruux* +
_identifier_: julien.haderer@dauphine.eu +
_password_ : azerty2022 +
_calendar_ : TestCalendar + 
*Evolution* +
Any account but connected to the Fruux calendar with these username and password +
_username_ : b3297394371 +
_password_ : g8tokd3q0hc2 +
*J-Confs* +
In the instance variables, same username and password as above and connect to the Fruux TestCalendar by his login +
_calendarID_ : 548d1281-4843-4582-8d68-aee8fe0c45da +

 
==== Evolution and J-Confs compared to Fruux

Evolution is an application that can be installed on Linux and allows you to consult and edit a Fruux calendar. +
After connecting the application with the Fruux calendar identified by the calendarID noticed above, any consultation or modification is effectively possible and automatically synchronized on the Fruux calendar. +
On the J-Confs side, thanks to the recent modifications to the GuiListConferences class, all these manipulations by the user are also possible. +


_What modifications are possible for the same Fruux calendar connected with Evolution and the Gui interface generated by GuiListConferences?_


* Modifications via Evolution visbiles by J-Confs?

All changes, whether creating or deleting a calendar entry, made via Evolution are synchronized with what is visible in the interface generated by GuiListConferences. The details (date, location, descirption, url) of the conference are also visible. +

* Modifications via J-Confs visible in Evolution ?

Likewise, all changes, whether creating or deleting calendar entries, made via the Gui application are synchronized with and visible in the Evolution calendar after it has been updated. The details (date, location, descirption, url) of the conference are also visible. 


===== What's wrong? Areas to work on?

* A refresh button on the GuiListConferences interface to see in real time the changes made via Evolution (instead of having to restart the program to see them appear on the interface)
* The J-Confs program does not currently allow, and contrary to what is allowed by Evolution, the indication of conference times, only the insertion of the date is allowed. In fact, in addition to the lack of precision that this absence causes, the interface cannot open if a conference with indicated times has been inserted in the calendar via Evolution. Indeed, an error is generated when calling the _getOnlineConferences_ call because this format is unexpected. Since we don't want to make the software more complex by adding a start and end time to the conference, we should find a way for the software to ignore the possible start time.
 

