locationiq-java-client
----------------------
Location IQ
. API version 1.1.0

LocationIQ provides flexible enterprise-grade location based solutions. 
We work with developers, startups and enterprises worldwide serving billions of requests everyday. 
This page provides an overview of the technical aspects of our API and will help you get started.



== Requirements

Building the API client library requires:

. Java 1.8+
. Maven/Gradle

== Installation

To install the API client library to your local Maven repository, simply execute:


-----------------
mvn clean install
-----------------
To deploy it to a remote Maven repository instead, configure the settings of the repository and execute:

-----------------
mvn clean deploy
-----------------
Refer to the https://central.sonatype.org/pages/ossrh-guide.html[OSSRH Guide] for more information.

== Maven users

Add this dependency to your project's POM:

-----------------
<dependency>
  <groupId>com.locationiq</groupId>
  <artifactId>locationiq-java-client</artifactId>
  <version>1.1.0</version>
  <scope>compile</scope>
</dependency>
-----------------

== Gradle users

Add this dependency to your project's build file:

-----------------
compile "com.locationiq:locationiq-java-client:1.1.0"
-----------------

== Others

At first generate the JAR by executing:

-----------------
mvn clean package
-----------------
Then manually install the following JARs:

- target/locationiq-java-client-1.1.0.jar
- target/lib/*.jar

== Getting started

Please follow the installation instruction and execute the following Java code:

-----------------
// Import classes:
import LocationIq.ApiClient;
import LocationIq.ApiException;
import LocationIq.Configuration;
import LocationIq.auth.*;
import LocationIq.models.*;
import com.locationiq.client.api.AutocompleteApi;

public class Example {
  public static void main(String[] args) {
    ApiClient defaultClient = Configuration.getDefaultApiClient();
    defaultClient.setBasePath("https://eu1.locationiq.com/v1");
    
    // Configure API key authorization: key
    ApiKeyAuth key = (ApiKeyAuth) defaultClient.getAuthentication("key");
    key.setApiKey("YOUR API KEY");
    // Uncomment the following line to set a prefix for the API key, e.g. "Token" (defaults to null)
    //key.setApiKeyPrefix("Token");

    AutocompleteApi apiInstance = new AutocompleteApi(defaultClient);
    String q = "Empire state"; // String | Address to geocode
    Integer normalizecity = 1; // Integer | For responses with no city value in the address section, the next available element in this order - city_district, locality, town, borough, municipality, village, hamlet, quarter, neighbourhood - from the address section will be normalized to city. Defaults to 1 for SDKs.
    Integer limit = 10; // Integer | Limit the number of returned results. Default is 10.
    String viewbox = "-132.84908,47.69382,-70.44674,30.82531"; // String | The preferred area to find search results.  To restrict results to those within the viewbox, use along with the bounded option. Tuple of 4 floats. Any two corner points of the box - `max_lon,max_lat,min_lon,min_lat` or `min_lon,min_lat,max_lon,max_lat` - are accepted in any order as long as they span a real box. 
    Integer bounded = 1; // Integer | Restrict the results to only items contained with the viewbox
    String countrycodes = "us"; // String | Limit search to a list of countries.
    String acceptLanguage = "en"; // String | Preferred language order for showing search results, overrides the value specified in the Accept-Language HTTP header. Defaults to en. To use native language for the response when available, use accept-language=native
    String tag = "place"; // String | Restricts the autocomplete search results to elements of specific OSM class and type.  Example - To restrict results to only class place and type city: tag=place:city, To restrict the results to all of OSM class place: tag=place
    try {
      List<Object> result = apiInstance.autocomplete(q, normalizecity, limit, viewbox, bounded, countrycodes, acceptLanguage, tag);
      System.out.println(result);
    } catch (ApiException e) {
      System.err.println("Exception when calling AutocompleteApi#autocomplete");
      System.err.println("Status code: " + e.getCode());
      System.err.println("Reason: " + e.getResponseBody());
      System.err.println("Response headers: " + e.getResponseHeaders());
      e.printStackTrace();
    }
  }
}
-----------------


== ReverseGeocode VS LocationIQ

*ReverseGeocode* : In our project, the Geocode package is used exclusively to store cities with their latitude and longitude. This information is retrieved by extracting a file. In our project, this is the file cities15000.txt (this file contains all cities with more than 15000 inhabitants). The limits of reverseGeocode are :

- Impossible to include a maven addiction. You have to download and include the whole package from the library.
- Cities are limited because of the file. Basically, we had tried to integrate a file containing all the cities of the world but because of the huge size of the file, the code took too long to answer (more than 10 minutes without answers).
- Basically, the aim is to find a short route from the researcher's starting point to the conference venue. With ReverseGeocode it is impossible to have a precise address, the route will only be approximate (from one city to another).

*LocationIQ* : To use LocationIQ (which will have to be implemented), we have to create an account in order to be able to query the different classes. The API seems much more flexible, since it is able to give the complete address via a label entered by the user. For example, if you type "Université Paris-Dauphine PSL", the API outputs a json file containing a lot of information including latitude, longitude but also the complete label. In our example, the important information are: lat: 48.862725 lon: 2.287592 and displayName: Université Paris-Dauphine PSL, Place du Maréchal de Lattre de Tassigny, Paris 16e Arrondissement, Paris, Île-de-France, 75016, France. The boundaries of LocationIQ are :

- You need an account to be able to use the online classes.
- Cities are limited because of the file. Basically, we had tried to integrate a file containing all the cities in the world but because of the huge size of the file, the code took too long to answer (more than 10 minutes without answers).

== To Conclude

So we chose to use locationIQ API.

We will make a location class that will have for attribute latitudeDep, longitudDep, latitudeArr, longitudeArr, villeDep, villeArr. This class will initialize longitude and latitude from a city name. This will be done by reading a file containing all the necessary information. It will also be possible to do in the other direction, that is to enter a latitude and longitude and obtain the name of the city.


*Strong points*:

- Everything we need is usable via this API and it seems easy to use
- Product routing
- Product geocoding

*Weak points*:

- Everything is free (10,000 requests per day, which is enough for the end of our project)
- Complicated installation