= Use a calendar on a cloud platform


The purpose of this document is to document the storage functionality of online conferences in a cloud platform.


A graphical user interface called "GuiListConferences" has been set up with the aim of displaying, editing and adding conferences to an online calendar storage website by the last team.


The calendar storage websites used are https://fruux.com/[Fruux^] or https://nextcloud.com/[NextCloud^]. It is a free service that allows you to keep your contacts and calendars synchronized on many platforms.


In order to be able to exchange data between the application and the hosts, it is necessary to use an online calendar editing protocol named *CalDav*.


The CalDav4j library has been chosen in order to allow these exchanges, it includes a set of methods allowing the edition of events and the addition of new events online. All the methods using this library are in the "CalendarOnline" class.

== Prerequisites :

	* A fruux account or a NextCloud account.
	* The calendar must be in ICalendar format. It contains a set of events represented by "VEvent" components, which must be named according to the naming standards.
- The "UID" property contains a unique identifier of an event.
- The "description" property contains the value of the conference fee.
- The "location" property contains the name of the city followed by the name of the country (fields separated by a comma) of the conference.
- The "summary" property contains the title of the event.

	* Within the Java code it is necessary to fill a document of configuration with a set of information to be retrieved on fruux or nextcloud. This information will allow you to have the authorization to retrieve events from a desired calendar. It is necessary to set :
- The calendar identification key.
- The user id.
- The user password.

	* You need to change user account in io.github.oliviercailloux.jconfs.calendar.TestCalendarOnlineFruux and io.github.oliviercailloux.jconfs.calendar.TestCalendarOnlineNextCloud when you have created yours.
It will be easier in case of issue. Nevertheless, this part of the code don't seems to have issue.
Be aware that if the server is unreachable, your test will fail and by so your maven test also.
 
More infos :

- Fruux : https://fruux.com/api/
- NextCloud : https://nextcloud.com/signup/
- Library : https://github.com/caldav4j/caldav4j/tree/master/src/example/org/osaf/caldav4j/example
- ICalendar : https://tools.ietf.org/html/rfc5545
- Old team documentation : https://github.com/13tomoore/J-Confs/blob/master/Doc/Documentation_CalendarOnline.adoc

