= How to modify JUnit tests in order to use them in the project ?

== Calendar Test

=== TestCalendarOnlineFruux

As seen in this https://github.com/oliviercailloux-org/projet-j-confs/blob/main/Doc/Prerequisites%20CalendarOnline.adoc[documentation], you need to first to change the calendar identification key, the user id and the user password in this https://github.com/oliviercailloux-org/projet-j-confs/blob/main/src/test/java/io/github/oliviercailloux/jconfs/calendar/TestCalendarOnlineFruux.java[test].
Then you need to create a calendar in your account, and set the calendarID in the code.

The test "testGetOnlineConferenceFromUid()" tries to find a specific conference in your calendar.

In order to make it work, you need to create a conference in your fruux account with these properties :
- Title : Java formation
- City : Paris
- Country : France
- Beginning Date : 2022-05-31
Make sure to check the "All day" item, when creating the conference in Fruux, because the test can't handle times.   
After that, you need to find the ID of the conference, and replace it in the "uidSearch" variable. 

=== TestCalendarOnlineNextCloud

You may need to make the same changes for the TestCalendarOnlineNextCloud test, but on your NextCoud account.