= Use a calendar on a cloud platform


The purpose of this document is to document the storage functionality of online conferences in a cloud platform.


A graphical user interface called "GuiListConferences" has been set up with the aim of displaying, editing and adding conferences to an online calendar storage website by the last team.


The calendar storage websites used are https://fruux.com/[Fruux^] or https://nextcloud.com/[NextCloud^]. It is a free service that allows you to keep your contacts and calendars synchronized on many platforms.


In order to be able to exchange data between the application and the hosts, it is necessary to use an online calendar editing protocol named *CalDav*.


The CalDav4j library has been chosen in order to allow these exchanges, it includes a set of methods allowing the edition of events and the addition of new events online. All the methods using this library are in the "CalendarOnline" class.

== Prerequisites :

	* A fruux account or a NextCloud account.
	* The calendar must be in ICalendar format. It contains a set of events represented by "VEvent" components, which must be named according to the naming standards.
- The "UID" property contains a unique identifier of an event.
- The "description" property contains the value of the conference fee.
- The "location" property contains the name of the city followed by the name of the country (fields separated by a comma) of the conference.
- The "summary" property contains the title of the event.

	* At the root of the project, it is necessary to create a document with the name "API_Credentials_SoftwareName.txt" in order to be able to connect the project with the different softwares via JARiS. It must contain those elements in this particular order:
** Username 
** Password 
** Url
** CalendarID 	

== How to modify JUnit tests in order to use them in the project ?

=== TestCalendarOnlineFruux

You need to change user account in io.github.oliviercailloux.jconfs.calendar.TestCalendarOnlineFruux and io.github.oliviercailloux.jconfs.calendar.TestCalendarOnlineNextCloud when you have created yours.

Then, you need to create a calendar in your account, and set the calendarID in the "TestCalendarOnlineFruux" method. You will find this ID in the parameters of your Fruux account.

The test "testGetOnlineConferenceFromUid()" tries to find a specific conference in your calendar.

In order to make it work, you need to create a conference in your fruux account with these properties :

* Title : Java formation.
* City : Paris.
* Country : France.
* Beginning Date : 2022-05-31.

Make sure to check the "All day" item, when creating the conference in Fruux, because the test can't handle times.   
After that, you need to find the ID of the conference, and replace it in the "uidSearch" variable. 
Tips to find this ID : Run the test after all the modifications. It will fail but you will see on the "Console" window, a list with all your conferences in your calendar with theirs characteristics.
You will find there the UID of the conference "Java formation"

=== TestCalendarOnlineNextCloud

You may need to make the same changes for the TestCalendarOnlineNextCloud test, but on your NextCloud account.
	

Be aware that if the server is unreachable, your test will fail and by so your maven test also.

 
== More infos :

- Fruux : https://fruux.com/api/
- NextCloud : https://nextcloud.com/signup/
- Library : https://github.com/caldav4j/caldav4j/tree/master/src/example/org/osaf/caldav4j/example
- ICalendar : https://tools.ietf.org/html/rfc5545
- Old team documentation : https://github.com/13tomoore/J-Confs/blob/master/Doc/Documentation_CalendarOnline.adoc

