= TODO

We will focus on the calendar functionality, in order to provide easy collective management of conferences at the level of a lab. In passing, we will also fix various defects in that part of the code.

* Create a Fruux account, make sure that the calendar aspects work as intended, document anything missing.
* Fix tests that fail
* Use https://github.com/oliviercailloux/JARiS[JARiS] to read the API key for accessing the calendar services
* Document the format used to store a conference (specify exactly which fields are used and why)
* Test whether Evolution can access and edit those calendar entries; document what works and what doesn’t
* Search how to store programmatically a precise location in a calendar entry (either in the form of a point, with a latitude and a longitude; or a specific city)
* Check how (or whether) Evolution can store a precise location in a calendar entry
* Permit a user to mark in the calendar entry that she wants to attend that conference (check whether this is visible in Evolution)
* Find the train station nearest to a given point (or city, see above)
* Find the price of a trip from Paris to a given train station (search, document and use an online service)
* Enter the estimated price of the trip in the conference entry

== Older requirements (to be translated and adapted)
* Utiliser https://github.com/oliviercailloux/JARiS[JARiS] pour lire la clé d’API pour accès aux services de calendrier en ligne ou LocationIQ
* Améliorer ou compléter documentation, implémentation, tests du package calendar pour permettre récupération et édition d’entrées calendrier sur Fruux et NextCloud ; si nécessaire.
* GUI pour visualiser les conférences du calendrier en ligne
* GUI pour ajouter une conférence au calendrier en ligne
* GUI pour modifier une conférence du calendrier en ligne
* S’assurer que `CalendarOnline` stocke des conférences dans un format qui est compris par les logiciels de manipulation de calendriers tels que `Evolution`. Documenter quels champs du standard iCal sont utilisés, en particulier, comment représenter un point précis sur le globe (latitude, longitude, adresse textuelle)
* Stocker une `Address` (point avec une description et des coordonnées) dans conférence au lieu ds champs de localisation actuels (`country`, `city`), pour une localisation précise
* Calcul en ligne de commande d’un trajet de Paris à une ville d’europe continentale reliée directement à Paris (exemple : Berlin, Bruxelles), en train, avec prix. Commencer par rédiger un rapport, au format Asciidoctor, investigant les API en ligne pour ce faire. (Essayer la Deutshe Bahn)
* GUI pour montrer le trajet
* Étendre aux trajets à plusieurs points (avec changements)
* Étendre aux trajets en avion ; en voiture
* Étendre aux trajets multi-modaux
* Le trajet est associé à une URL qui permet de l’afficher sur une carte (https://www.openstreetmap.org/directions?engine=osrm_car&route=48.857%2C2.352%3B52.517%2C13.389#map=7/50.716/7.866[Exemple])
* Améliorer éventuellement documentation de https://github.com/mapsforge/mapsforge[Mapsforge] (https://www.javadoc.io/doc/org.mapsforge/mapsforge-map-reader/0.8.0/index.html[Javadoc]), étudier la possibilité de l’utiliser pour afficher le trajet directement
* Étendre la fonctionalité d’enregistrement d’un prix (`registrationFee`) d’une conférence pour permettre des prix différenciés : student price, early registration fee, member price, …
* Étudier la possibilité d’utiliser https://geotools.org/[`GeoTools`] pour calculer des distances ou temps de parcours en voiture entre endroits sur le globe, ou convertir entre adresses et coordonnées, en vue de remplacer LocationIQ, et comparer à la solution actuelle
* Nettoyer ressources (16 MB dans src/main/resources/io/github/oliviercailloux/jconfs)
* Chercher les informations concernant un chercheur à l’aide de Supann, cf. https://github.com/Dauphine-MIDO/plaquette-MIDO[Plaquette MIDO]
* Étudier existence d’une API plus moderne pour manipuler des documents OpenDocument
* Modifier canevas existant LibreOffice Writer, insérer des champs d’utilisateur tels que Researcher_name ou Conference_name (dans LibreOffice : menu Insertion / Champ / Autres champs / Variables), et faire en sorte que ces champs soient mis à la bonne valeur
* GUI pour générer un document LibreOffice (cf. ci-dessus)
* L’ensemble du calendrier doit pouvoir être envoyé sur un dépot existant GitHub créé (manuellement) à cet effet. Après modification de conférences (à la sortie de l’application ou toutes les 30 minutes), le nouveau calendrier est envoyé sur le dépôt existant, pour sauvegarde (permet de restaurer une version précédente en cas d’effacement maladroit, par exemple)
* L’utilisateur peut ajouter des entrées de dépenses (par exemple, dépenses sur place) qui s’ajoutent à la note
* Serveur web qui renvoie un canevas LibreOffice sur base du login d’un chercheur
* Génération du formulaire annuel de demande de PRES (voir https://github.com/oliviercailloux/projets/blob/master/LAMSADE/PRES.pdf[canevas] PRES), d’après données passées en paramètres / fournies par interface graphique / récupérée depuis fichier / récupérée depuis internet
* L’utilisateur peut entrer son mot de passe de son compte e-mail @dauphine. Le logiciel le stocke en suivant le mécanisme de conservation des données secrètes de l’OS.
* Réception des demandes scannées envoyées sur l’e-mail du chercheur (reconnaissable par l’adresse expéditeur : \photocopieur@lamsade.dauphine.fr), à la demande de l’utilisateur.
* Envoi demande par e-mail.
* Pouvoir publier son trajet, en vue par exemple de voyager avec ses collègues

