= Calendar package
:toc:
:sectanchors:

First you need to create some account.


The package calendar permits to use an online calendar or to use a local file file calendar with limited options. To use an online calendar you need first, to set credential providers in order to connect to the calendar, thanks to JARiS.

image:https://github.com/oliviercailloux-org/projet-j-confs/Doc/Papyrus/Diagrams/JARiS_use_case_diagramm.SVG[alt="JARiS use case diagram",width=80%,height=80%, align="center"]

image:https://github.com/oliviercailloux-org/projet-j-confs/Doc/Papyrus/Diagrams/CredentialsReader_Class_Diagramm.SVG[alt="JARiS Class diagram",width=80%,height=80%, align="center"]


After that, you can add, edit, delete, and get online conferences.

=== Use case diagram

image:https://github.com/sebastienbourg/J-Confs/blob/master/Doc/Papyrus/Diagrams/Calendar_use_case_diagram.SVG[alt="Calendar use case diagram",width=80%,height=80%, align="center"]

By connecting with a local calendar you can only create a conference.

This use case is a detailed version of the general use case about one or several specific use cases. It details the following use cases:

* https://github.com/sebastienbourg/J-Confs/blob/master/Doc/UML%20documentation/General_View.adoc#use-case-diagram[Manage online calendar] 

* https://github.com/sebastienbourg/J-Confs/blob/master/Doc/UML%20documentation/General_View.adoc#use-case-diagram[Visualize conferences in an online calendar]

This diagram is accessible from the general view use case via a hyperlink (click on the use case in Papyrus model).

=== Class diagram

image:https://github.com/sebastienbourg/J-Confs/blob/master/Doc/Papyrus/Diagrams/Calendar_s_class_diagram.SVG[alt="Calendar use case diagram",width=80%,height=80%, align="center"]

In this package that is represented in Papyrus, we have 4 classes : CalendarOnline, CalendarConnector, UserCredentials and ReadCalendarFiles.

* CalendarOnline manage a calendar. 
* CalendarConnector connect to the calendar. 
* UserCredentials read a JSON file and give credential to CalendarConnector.
* ReadCalendarFiles can read ics file.

=== Sequence diagram

image:https://github.com/sebastienbourg/J-Confs/blob/master/Doc/Papyrus/Diagrams/Sequence_Diagram_CalendarOnline_getOnlineConferences.SVG[alt="Calendar use case diagram",width=80%,height=80%, align="center"]

Here you can find how we look for online conferences. 

=== What could be done next

In the Calendar packages, there are some changes to be made to improve the code, make it "cleaner", improve functions or remove unnecessary things. There are for example :

* You can try to increase the number of calendar useable by the user. By so, I mean find a NextCloud/Fruux like.
* Add a function to send to git and add a function restore from git in CalendarOnline the whole calendar. 
* Add a function that help us to know if the calendar is writeable/readable in ReadCalendarFiles. 
* You can also use Path instead of String as seen in course.

