= Evolution, fruux and J-Confs

== Evolution and J-Confs compared to Fruux 
Evolution is an application that can be installed on Linux and allows you to consult and edit a fruux calendar.
After connecting the application with a fruux calendar identified by 548d1281-4843-4582-8d68-aee8fe0c45da, any consultation or modification is effectively possible and automatically synchronized on fruux.
On the J-Confs side, thanks to the recent modifications to the GuiListConferences class, all these manipulations by the user are also possible.

---> For the same fruux calendar connected with Evolution and the Gui interface generated by GuiListConferences 

== Modifications via Evolution visbiles by J-Confs?
All changes, whether creating or deleting a calendar entry, made via Evolution are synchronized with what is visible in the interface generated by GuiListConferences. The details (date, location, descirption, url) of the conference are also visible. 

== Modifications via J-Confs visible in Evolution ?
Likewise, all changes, whether creating or deleting calendar entries, made via the Gui application are synchronized with and visible in the Evolution calendar after it has been updated. The details (date, location, descirption, url) of the conference are also visible. 

--> What's wrong? Areas to work on?

1- A refresh button on the GuiListConferences interface to see in real time the changes made via Evolution (instead of having to restart the program to see them appear on the interface)
2- The J-Confs program does not currently allow, and contrary to what is allowed by Evolution, the indication of conference times, only the insertion of the date is allowed. In fact, in addition to the lack of precision that this absence causes, the interface cannot open if a conference with indicated times has been inserted in the calendar via Evolution. Indeed, an error is generated when calling the getOnlineConferences call because this format is unexpected. 
Adding the possibility of a time field in the software when creating a conference would be very useful. 
 

